### ISSUE TITLE
Hi..when i first run main.py -- eval,appeared [list] no define 

### ISSUE THREAD

**Issue by zouzouwei** [ShoufaChen/CycleMLP#1]
![image](https://user-images.githubusercontent.com/15826704/126757452-ca079274-9f57-4388-9740-dcd143b4061c.png)
As shown in the diagram

**Comment by ShoufaChen** [comment]
Hi, @zouzouwei 

I just updated the code.

Please try again.

**Comment by zouzouwei** [comment]
THX
