### ISSUE TITLE
detection result

### ISSUE THREAD

**Issue by mountain111** [ShoufaChen/CycleMLP#12]
Applying PVT detection framework, I tried a CycleMLP-B1 based detector with RetinaNet 1x.
I got AP=27.1, fairly inferior to the reported 38.6. Could you give some advices to reproduce the reported result?

The specific configure is as follows

_base_ = [
    '_base_/models/retinanet_r50_fpn.py',
    '_base_/datasets/coco_detection.py',
    '_base_/schedules/schedule_1x.py',
    '_base_/default_runtime.py'
]
#optimizer
model = dict(
    pretrained='./pretrained/CycleMLP_B1.pth',
    backbone=dict(
        type='CycleMLP_B1_feat',
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[64, 128, 320, 512],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5))
#optimizer
optimizer = dict(_delete_=True, type='AdamW', lr=0.0001, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)

find_unused_parameters = True

**Comment by ShoufaChen** [comment]
I am sorry but I need the log information about loading the pretrained model, which is not included.

**Comment by mountain111** [comment]
Thanks a lot for your reply!
Previously, the pretrained model was not loaded. Now, I add an initialization method for pretrained models.
Hope the result can be improved.
