### ISSUE TITLE
Swin-B vs CycleMLP-B on image classification 

### ISSUE THREAD

**Issue by hkzhang91** [ShoufaChen/CycleMLP#13]
For classificaion on ImageNet-1k, the acuracy of Swin-B is 83.5, which is 0.1 higher than the proposed CycleMLP-B. But, in this paper, the authors reprot that the accuracy of Swin-B is 83.3, which is 0.1 lower than the proposed CycleMLP-B. Why are these accuracies different?

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

We reported Swin-B (83.3) following the original Swin arxiv paper (Table 1 a): https://arxiv.org/pdf/2103.14030v1.pdf


I noticed that they updated this value in the latest version.
