### ISSUE TITLE
Questions about offset calculation

### ISSUE THREAD

**Issue by tae-mo** [ShoufaChen/CycleMLP#14]
Hi, thanks for your wonderful work.

I'm currently studying your work, 
and come up with some question about the offset calculations.

I understood the offset calculation mentioned on the paper, 
but can't understand about how generated offset is being used in the code.

For ex)
if $S_H \times S_W : 3 \times 1$;
I understood how the offset is applied in this figure
<img width="404" alt="스크린샷 2022-06-13 오후 9 18 20" src="https://user-images.githubusercontent.com/50903158/173351796-fadc4501-9061-4968-bd7b-dda7a4b13ba8.png">

by calculate like this:
<img width="577" alt="스크린샷 2022-06-13 오후 9 19 57" src="https://user-images.githubusercontent.com/50903158/173352075-8cc4387d-b16b-4245-9f74-0398e0208a37.png">

However, when I run the offset generating code, 
I can't figure out how this offset is being used in deform_conv2d
<img width="870" alt="스크린샷 2022-06-13 오후 9 21 57" src="https://user-images.githubusercontent.com/50903158/173352458-890e56cf-34b2-4821-855d-2392baa19937.png">

Can you provide more detailed information about this??

And also, the paper contains how $S_H \times S_W: 3 \times 3$ works,
but in the code, it seems like either one of```kernel_size[0]``` or ```kernel_size[1]``` has to be 1.
So, if I want to use $S_H \times S_W : 3 \times 3$,
do I have to make $3 \times 1$ and $1 \times 3$ offsets and add those together?

Thank you again for your work.
I really learned a lot.

**Comment by ShoufaChen** [comment]
Hi, Thanks for your interest.

The offset you calculated using code is `[0, 0, 1, 0, -1, 0]`,  which denotes
|channel | x | y |
|--------|---|--|
| 0 | 0 |0 |
|1 | 1 | 0| 
|2| -1| 0|

It differs from the figure as their cyclic periods start at different points.  It makes negligible as this is a cycle sampling process.

For kernel 3x3, you should use the cyclic pattern over two dimensions, ie, H and W.

**Comment by tae-mo** [comment]
Thanks for the quick reply.

So if that is applied in Figure 7-(c),
<img width="446" alt="스크린샷 2022-06-13 오후 10 05 13" src="https://user-images.githubusercontent.com/50903158/173360192-24b62829-dc06-4040-9999-5268a8084e7c.png"> 
is it correct to think that the start point starts at the second channel?

Because as you explained, 
if the offset x and y are (0, 0), (1, 0), and (-1, 0),
the starting point has to be started at channel 1 in the Figure 7 to have x offset as 0 -> 1 -> -1.

Am I correct?

**Comment by tae-mo** [comment]
> 

I understand that it differs from where it starts,
but I wanted to make sure that I understood it correctly.

Thanks!

**Comment by ShoufaChen** [comment]
Yes, your understanding is correct.

**Comment by tae-mo** [comment]
Thank you very much for your kind explanation!
Have a great day◡̈
