### ISSUE TITLE
Compiling CycleMLP

### ISSUE THREAD

**Issue by shairoz-deci** [ShoufaChen/CycleMLP#4]
Thank you for this great repo and interesting paper.

I tried compiling CycleMLP to onnx and not surpassingly the process failed since CycleMLP include dynamic offset creation in
https://github.com/ShoufaChen/CycleMLP/blob/main/cycle_mlp.py#L132
and as such cannot be converted to a frozen graph. 
Were you able to convert CycleMLP to onnx or any other frozen graph framework?

Thanks in advance.

**Comment by ShoufaChen** [comment]
Hi, @shairoz-deci 

Thanks for your interest in our work.

In fact, the offset creation process is not dynamic.

It is easy to remove the `if-else` in offset generation by using two independent `get_offset` functions, one for `H` and the other for `W`.

**Comment by shairoz-deci** [comment]
Thank you @ShoufaChen for the quick response.
I'm afraid I didn't understand your intention, can you please elaborate or provide a code snippet to the changes that needs to be made on order to compile CycleMLP.

Thanks

**Comment by ShoufaChen** [comment]
Hi, @shairoz-deci 

Sorry for my late reply.

You can fork this repo (as I don't want to change the main structure of this repo currently) and I will provide the changes I mentioned above for your requirement throng pull request.

**Comment by shairoz-deci** [comment]
forked
https://github.com/shairoz-deci/CycleMLP

Thanks

**Comment by ShoufaChen** [comment]
Hi, 

Would you mind providing more details about the compiling issue you met?

**Comment by ShoufaChen** [comment]
Closing for a long time no response.
feel free to re-open if you still have problems.
