### ISSUE TITLE
1D

### ISSUE THREAD

**Issue by aslarsen** [ShoufaChen/CycleMLP#6]
Hi
Would it be possible to change the CycleMLP for 1D data instead of the 2D images? And would there be any benefit?

**Comment by ShoufaChen** [comment]
Hi, @aslarsen 

Thanks for your interest.

I think it's easy to use CycleMLP for 1D data.

For 2D image, there is  `H` and `W` branchs defined here:
https://github.com/ShoufaChen/CycleMLP/blob/2f76a1f6e3cc6672143fdac46e3db5f9a7341253/cycle_mlp.py#L167-L168


For 1D data, I think you can just use a single branch.

Best.
