### ISSUE TITLE
Example of CycleMLP Configuration for Dense Prediction

### ISSUE THREAD

**Issue by amorehead** [ShoufaChen/CycleMLP#7]
Hello.

First of all, thank you for curating this interesting work. I was wondering, are there any working examples of how I can use CycleMLP for dense prediction while maintaining the original input size (e.g., predict a 0 or 1 value for each pixel in an input image)? In addition, I am interested in only a single ("annotated") output image, although I noticed the model definitions given in this repository output multiple downsampled versions of the original input image. Any thoughts on this?

Thank you in advance for your time.

**Comment by ShoufaChen** [comment]
Hi,

Thanks for your interest.

The task you mentioned above seems close to semantic segmentation.

If so, we have conducted experiments on ADE20K semantic segmentation (results are presented in arxiv paper).

The corresponding code is mostly borrowed from [PVT repo](https://github.com/whai362/PVT/tree/v2/segmentation). We'll release this part of code in the near future.


If you are interested in only a single output image, you can choose the one you like from the output list. 

E.g.` output = [feat1, feat2, feat3]`, you can just use `output[-1]` to index the last feature if you want.

**Comment by amorehead** [comment]
@ShoufaChen,

Thank you for your timely response. I greatly appreciate it, and thank you also for pointing out which representations to extract. I look forward to viewing your semantic segmentation code once it is released.
